//
//  Oven.swift
//  EggieRun
//
//  Created by Liu Yang on 17/4/16.
//  Copyright © 2016 Eggieee. All rights reserved.
//

// Class: Oven
// Description: a subclass of Obstacle. Eggie has to jump over it or 
// jump on the top of it to avoid death. If Eggie is killed by a Oven, 
// a dish will be generated by baking Eggie.

import SpriteKit

class Oven: Obstacle {
    fileprivate static let IMAGE_NAME = "oven-open"
    fileprivate static let ATLAS_NAME = "oven-close.atlas"
    fileprivate static let PADDING: CGFloat = -27
    
    fileprivate var body: SKSpriteNode
    
    init() {
        body = SKSpriteNode(imageNamed: Oven.IMAGE_NAME)
        body.scale(Obstacle.WIDTH)
        body.position.x = body.size.width / 2
        body.position.y = body.size.height / 2
        body.physicsBody = SKPhysicsBody(rectangleOf: body.size)
        body.physicsBody!.categoryBitMask = BitMaskCategory.obstacle
        body.physicsBody!.contactTestBitMask = BitMaskCategory.hero
        body.physicsBody!.collisionBitMask = BitMaskCategory.hero | BitMaskCategory.obstacle
        body.physicsBody!.isDynamic = false
        
        super.init(cooker: .oven)
        heightPadding = Oven.PADDING
        addChild(body)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func isDeadly(_ vector: CGVector, point: CGPoint) -> Bool {
        return abs(vector.dy) < 0.5
    }
    
    override func animateClose() {
        let atlas = SKTextureAtlas(named: Oven.ATLAS_NAME)
        let textures = atlas.textureNames.sorted().map({ atlas.textureNamed($0) })
        body.run(SKAction.repeatForever(SKAction.animate(with: textures, timePerFrame: Obstacle.ATLAS_TIME_PER_FRAME)))
    }
}
