//
//  Pot.swift
//  EggieRun
//
//  Created by Liu Yang on 17/4/16.
//  Copyright © 2016 Eggieee. All rights reserved.
//

// Class: Pot
// Description: a subclass of Obstacle, Eggie has to jump over it or 
// jump on the top of it to avoid death. If Eggie is killed by a Pot, 
// a dish will be generated by boiling Eggie.

import SpriteKit

class Pot: Obstacle {
    private static let IMAGE_NAME_BODY = "pot-body"
    private static let IMAGE_NAME_LID = "pot-lid"
    private static let PADDING: CGFloat = -20
    private static let LID_HEIGHT: CGFloat = 80
    private static let NUM_FRAME: Double = 2

    private var body: SKSpriteNode
    private var lid: SKSpriteNode

    init() {
        body = SKSpriteNode(imageNamed: Pot.IMAGE_NAME_BODY)
        body.scale(Obstacle.WIDTH)
        body.position.x = body.size.width / 2
        body.position.y = body.size.height / 2
        body.physicsBody = SKPhysicsBody(rectangleOfSize: body.size)
        body.physicsBody!.categoryBitMask = BitMaskCategory.obstacle
        body.physicsBody!.contactTestBitMask = BitMaskCategory.hero
        body.physicsBody!.collisionBitMask = BitMaskCategory.hero | BitMaskCategory.obstacle
        body.physicsBody!.dynamic = false
        
        lid = SKSpriteNode(imageNamed: Pot.IMAGE_NAME_LID)
        lid.scale(Obstacle.WIDTH)
        lid.position.x = lid.size.width / 2
        lid.position.y = lid.size.height / 2 + Pot.LID_HEIGHT
        lid.physicsBody = SKPhysicsBody(rectangleOfSize: lid.size)
        lid.physicsBody!.categoryBitMask = BitMaskCategory.obstacle
        lid.physicsBody!.contactTestBitMask = BitMaskCategory.hero
        lid.physicsBody!.collisionBitMask = BitMaskCategory.hero | BitMaskCategory.obstacle
        lid.physicsBody!.dynamic = false
        
        super.init(cooker: .Pot)
        heightPadding = Pot.PADDING
        addChild(body)
        addChild(lid)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func isDeadly(vector: CGVector, point: CGPoint) -> Bool {
        return abs(vector.dy) < 0.5
    }
    
    override func animateClose() {
        lid.runAction(SKAction.moveBy(CGVectorMake(0, body.size.height - Pot.LID_HEIGHT), duration: Obstacle.ATLAS_TIME_PER_FRAME * Pot.NUM_FRAME))
    }
}